/**
 * The Learn English word list.
 *
 * TTMS is not translated, on purpose — the company works in English with US
 * clients and carriers, and the point is to help people read it, not to route
 * around it. When somebody turns on Learn English (see LearnContext), every
 * word on this list gets a dotted underline wherever it appears on screen, and
 * hovering or tapping it opens a card with the Spanish, a plain-English
 * meaning and an example.
 *
 * **Written by hand, not machine-translated, and that is the feature.** A
 * translation service turns "consignee" and "lane" into nonsense, and those are
 * exactly the words somebody new to freight does not know. The Spanish leans
 * Guatemalan where the two differ ("piloto", "marchamo", "bodega") because that
 * is where the team is.
 *
 * Plain data, no Firestore and no DOM, so the words page, the underliner and
 * the API route that validates ids all read the same list. **An id is stored**
 * in each person's `vocabulary/{uid}` record, so renaming one orphans their
 * history for that word — add a new id rather than changing an old one.
 * Changing a word's text, Spanish or meaning is free.
 */

export type GlossaryCategory =
  | 'loads'
  | 'companies'
  | 'money'
  | 'paperwork'
  | 'trucks'
  | 'screen'
  | 'office';

export const GLOSSARY_CATEGORY_LABEL: Record<GlossaryCategory, string> = {
  loads:     'Loads and orders',
  companies: 'Companies and people',
  money:     'Money',
  paperwork: 'Paperwork',
  trucks:    'Trucks and equipment',
  screen:    'Words on the screen',
  office:    'Office English',
};

export interface GlossaryTerm {
  /** Stored in `vocabulary/{uid}.words` — never rename one. */
  id: string;
  /** The form shown at the top of the card. */
  word: string;
  /** Spanish, as short as it can be while still being right. */
  es: string;
  /** Plain English, one sentence, words a learner already knows. */
  meaning: string;
  /** A sentence somebody here might actually say or read. */
  example: string;
  category: GlossaryCategory;
  /**
   * Other spellings that open the same card. Leave it out and the plural is
   * worked out (see pluralOf); give an empty list for a word that has none.
   *
   * A form written all in capitals — BOL, ETA, MC — matches only in capitals,
   * so "pod" in a sentence is not mistaken for a proof of delivery.
   */
  forms?: string[];
}

export const GLOSSARY: GlossaryTerm[] = [
  // ── Loads and orders ──────────────────────────────────────────────────────
  { id: 'load', word: 'load', es: 'carga', category: 'loads',
    meaning: 'One shipment that one truck moves from one place to another.',
    example: 'We booked three loads for this client today.' },
  { id: 'order', word: 'order', es: 'orden', category: 'loads',
    meaning: 'Our record of one load: who, what, where, when and how much.',
    example: 'Open the order to check the pickup date.' },
  { id: 'freight', word: 'freight', es: 'carga, mercancía', category: 'loads', forms: [],
    meaning: 'The goods being moved by truck.',
    example: 'The freight is 20 pallets of paper towels.' },
  { id: 'shipment', word: 'shipment', es: 'envío', category: 'loads',
    meaning: 'Goods sent from one place to another.',
    example: 'The shipment left the warehouse this morning.' },
  { id: 'commodity', word: 'commodity', es: 'mercancía, tipo de producto', category: 'loads',
    forms: ['commodities'],
    meaning: 'What the freight is, for example frozen chicken or steel pipe.',
    example: 'Write the commodity so the carrier knows what they are hauling.' },
  { id: 'quote', word: 'quote', es: 'cotización', category: 'loads',
    forms: ['quotes', 'quoted', 'quoting'],
    meaning: 'A price we offer a client before they agree to the load.',
    example: 'Send the client a quote for Dallas to Chicago.' },
  { id: 'stale', word: 'stale', es: 'viejo, sin movimiento', category: 'loads', forms: [],
    meaning: 'Old, and nobody has done anything with it for a while.',
    example: 'Follow up on your stale quotes or close them.' },
  { id: 'book', word: 'book', es: 'reservar, confirmar', category: 'loads',
    forms: ['books', 'booked', 'booking', 'bookings'],
    meaning: 'To confirm a load: the client agreed and it is ours to move.',
    example: 'The load is booked; now we need a carrier.' },
  { id: 'dispatch', word: 'dispatch', es: 'despachar, despacho', category: 'loads',
    forms: ['dispatched', 'dispatches', 'dispatching'],
    meaning: 'To send a truck and driver to do a load. Also the team that does it.',
    example: 'Dispatch will call the driver before pickup.' },
  { id: 'dispatcher', word: 'dispatcher', es: 'despachador(a)', category: 'loads',
    meaning: 'The person who plans the trucks and keeps in touch with the drivers.',
    example: 'Ask the carrier’s dispatcher where the truck is.' },
  { id: 'lane', word: 'lane', es: 'ruta', category: 'loads',
    meaning: 'The route of a load: from the origin city to the destination city.',
    example: 'Dallas to Chicago is one of our busiest lanes.' },
  { id: 'origin', word: 'origin', es: 'origen', category: 'loads',
    meaning: 'The place where the load starts.',
    example: 'The origin is Laredo, Texas.' },
  { id: 'destination', word: 'destination', es: 'destino', category: 'loads',
    meaning: 'The place where the load ends.',
    example: 'The destination is a warehouse in Atlanta.' },
  { id: 'pickup', word: 'pickup', es: 'recolección, carga', category: 'loads',
    forms: ['pickups', 'pick-up', 'pick-ups', 'pick up', 'picked up', 'picking up'],
    meaning: 'When and where the truck collects the freight.',
    example: 'Pickup is tomorrow at 8 am.' },
  { id: 'delivery', word: 'delivery', es: 'entrega', category: 'loads',
    forms: ['deliveries', 'deliver', 'delivers', 'delivering'],
    meaning: 'When and where the truck drops off the freight.',
    example: 'The delivery window is 9 am to noon.' },
  { id: 'delivered', word: 'delivered', es: 'entregado', category: 'loads', forms: [],
    meaning: 'The freight has arrived and been dropped off.',
    example: 'Mark the load delivered once you have the POD.' },
  { id: 'in-transit', word: 'in transit', es: 'en tránsito, en camino', category: 'loads', forms: [],
    meaning: 'The freight is on the truck, on its way.',
    example: 'The load is in transit and should arrive Friday.' },
  { id: 'completed', word: 'completed', es: 'completado, cerrado', category: 'loads',
    forms: ['complete', 'completes'],
    meaning: 'Finished: delivered, paperwork in, and closed out.',
    example: 'The order is completed, nothing left to do.' },
  { id: 'cancelled', word: 'cancelled', es: 'cancelado', category: 'loads',
    forms: ['canceled', 'cancel', 'cancels', 'cancellation'],
    meaning: 'Stopped. The load will not move.',
    example: 'The client cancelled the load this morning.' },
  { id: 'status', word: 'status', es: 'estado, estatus', category: 'loads', forms: ['statuses'],
    meaning: 'Where something is right now, for example booked or in transit.',
    example: 'Change the status to delivered.' },
  { id: 'suborder', word: 'suborder', es: 'suborden', category: 'loads',
    meaning: 'A smaller order inside a bigger one, with its own truck and dates.',
    example: 'Split the freight into two suborders.' },
  { id: 'stop', word: 'stop', es: 'parada', category: 'loads',
    meaning: 'A place the truck stops to pick up or drop off freight.',
    example: 'This load has two stops before the final delivery.' },
  { id: 'appointment', word: 'appointment', es: 'cita', category: 'loads',
    meaning: 'A fixed time the warehouse expects the truck.',
    example: 'The consignee needs an appointment to unload.' },
  { id: 'eta', word: 'ETA', es: 'hora estimada de llegada', category: 'loads', forms: ['ETAs'],
    meaning: 'Estimated time of arrival: when the truck should get there.',
    example: 'What is the driver’s ETA?' },
  { id: 'check-call', word: 'check call', es: 'llamada de seguimiento', category: 'loads',
    meaning: 'A call to the driver or carrier to ask where the truck is.',
    example: 'Do a check call at noon.' },
  { id: 'on-time', word: 'on time', es: 'a tiempo', category: 'loads', forms: [],
    meaning: 'At the time that was agreed, not late.',
    example: 'The truck delivered on time.' },
  { id: 'late', word: 'late', es: 'tarde, atrasado', category: 'loads', forms: [],
    meaning: 'After the time that was agreed.',
    example: 'The driver is running two hours late.' },
  { id: 'weight', word: 'weight', es: 'peso', category: 'loads',
    meaning: 'How heavy the freight is, usually in pounds (lbs).',
    example: 'The weight is 42,000 lbs.' },
  { id: 'pallet', word: 'pallet', es: 'tarima', category: 'loads',
    meaning: 'A flat wooden base that freight is stacked on.',
    example: 'The load is 26 pallets.' },
  { id: 'piece', word: 'piece', es: 'pieza, bulto', category: 'loads',
    meaning: 'One item counted in the freight.',
    example: 'Count the pieces before the driver signs.' },
  { id: 'dimension', word: 'dimension', es: 'medida', category: 'loads',
    meaning: 'A size: length, width or height.',
    example: 'Add the dimensions of each pallet.' },
  { id: 'ltl', word: 'LTL', es: 'carga consolidada', category: 'loads', forms: [],
    meaning: 'Less than truckload: a small shipment that shares a truck with others.',
    example: 'Four pallets is an LTL shipment.' },
  { id: 'full-truckload', word: 'full truckload', es: 'camión completo', category: 'loads',
    forms: ['FTL', 'truckload', 'truckloads'],
    meaning: 'A shipment that fills a whole truck by itself.',
    example: 'This is a full truckload, 26 pallets.' },
  { id: 'hazmat', word: 'hazmat', es: 'materiales peligrosos', category: 'loads', forms: [],
    meaning: 'Hazardous materials: freight that is dangerous and has special rules.',
    example: 'Only some carriers can haul hazmat.' },

  // ── Companies and people ──────────────────────────────────────────────────
  { id: 'client', word: 'client', es: 'cliente', category: 'companies',
    meaning: 'The company that pays us to move its freight.',
    example: 'The client signed the load confirmation.' },
  { id: 'shipper', word: 'shipper', es: 'remitente, lugar de carga', category: 'companies',
    meaning: 'The place where the freight is picked up.',
    example: 'The shipper opens at 7 am.' },
  { id: 'consignee', word: 'consignee', es: 'destinatario, lugar de entrega', category: 'companies',
    meaning: 'The place that receives the freight.',
    example: 'The consignee is a warehouse in Memphis.' },
  { id: 'carrier', word: 'carrier', es: 'transportista', category: 'companies',
    meaning: 'The trucking company that moves the load for us.',
    example: 'We need a carrier for this load by tonight.' },
  { id: 'broker', word: 'broker', es: 'bróker, intermediario de carga', category: 'companies',
    forms: ['brokers', 'brokerage'],
    meaning: 'A company, like us, that connects clients with carriers. We do not own trucks.',
    example: 'As the broker, we find the truck and handle the paperwork.' },
  { id: 'driver', word: 'driver', es: 'piloto, conductor', category: 'companies',
    meaning: 'The person driving the truck.',
    example: 'Get the driver’s name and phone number.' },
  { id: 'facility', word: 'facility', es: 'instalación, planta', category: 'companies',
    forms: ['facilities'],
    meaning: 'A building where freight is loaded or unloaded.',
    example: 'The facility closes at 3 pm on Fridays.' },
  { id: 'warehouse', word: 'warehouse', es: 'bodega', category: 'companies',
    meaning: 'A large building where goods are stored.',
    example: 'The freight is waiting at the warehouse.' },
  { id: 'dock', word: 'dock', es: 'andén, muelle de carga', category: 'companies',
    meaning: 'The door at a warehouse where trucks load and unload.',
    example: 'The driver is at dock 4.' },
  { id: 'party', word: 'party', es: 'parte, empresa', category: 'companies', forms: ['parties'],
    meaning: 'Any company on an order: a client, a shipper or a consignee.',
    example: 'Add the party before you create the order.' },
  { id: 'owner', word: 'owner', es: 'responsable, dueño', category: 'companies',
    forms: ['owners', 'owned', 'ownership'],
    meaning: 'The person in charge of a client or an order.',
    example: 'Ask the owner of this client before you book it.' },
  { id: 'lead', word: 'lead', es: 'prospecto, cliente potencial', category: 'companies',
    meaning: 'A company that might become a client.',
    example: 'I got a new lead from a trade show.' },
  { id: 'lead-source', word: 'lead source', es: 'origen del prospecto', category: 'companies',
    meaning: 'How we first found a client, for example a referral or a website.',
    example: 'Set the lead source when you add the client.' },
  { id: 'book-of-business', word: 'book of business', es: 'cartera de clientes', category: 'companies',
    forms: [],
    meaning: 'All the clients and loads one person looks after.',
    example: 'Her book of business grew a lot this year.' },
  { id: 'team', word: 'team', es: 'equipo', category: 'companies',
    meaning: 'A group of people who work together under one leader.',
    example: 'Our team meets on Mondays.' },
  { id: 'work-group', word: 'work group', es: 'grupo de trabajo', category: 'companies',
    meaning: 'People who share the same clients and loads.',
    example: 'Add her to the work group so she can see those loads.' },
  { id: 'sales-manager', word: 'sales manager', es: 'gerente de ventas', category: 'companies',
    meaning: 'The person who leads a team of brokers.',
    example: 'Your sales manager can update your permissions.' },
  { id: 'intern', word: 'intern', es: 'practicante, pasante', category: 'companies',
    meaning: 'Somebody learning the job for a short time.',
    example: 'The new intern starts on Monday.' },
  { id: 'colleague', word: 'colleague', es: 'compañero(a) de trabajo', category: 'companies',
    meaning: 'A person you work with.',
    example: 'Send the file to a colleague in chat.' },

  // ── Money ─────────────────────────────────────────────────────────────────
  { id: 'rate', word: 'rate', es: 'tarifa, precio', category: 'money',
    meaning: 'The price for a load.',
    example: 'What rate did the carrier ask for?' },
  { id: 'agreed-rate', word: 'agreed rate', es: 'tarifa acordada', category: 'money', forms: [],
    meaning: 'The price the client agreed to pay us.',
    example: 'The agreed rate is $2,400.' },
  { id: 'carrier-pay', word: 'carrier pay', es: 'pago al transportista', category: 'money', forms: [],
    meaning: 'What we pay the carrier for the load.',
    example: 'Carrier pay is $2,000, so we keep $400.' },
  { id: 'broker-fee', word: 'broker fee', es: 'comisión del bróker', category: 'money',
    meaning: 'What we earn for arranging the load.',
    example: 'The broker fee on this load is $400.' },
  { id: 'margin', word: 'margin', es: 'margen, ganancia', category: 'money',
    meaning: 'What we keep: what the client pays minus what we pay the carrier.',
    example: 'The margin on this lane is too small.' },
  { id: 'gross-margin', word: 'gross margin', es: 'margen bruto', category: 'money', forms: [],
    meaning: 'The margin before office costs and salaries are taken out.',
    example: 'Our gross margin this month is 15%.' },
  { id: 'revenue', word: 'revenue', es: 'ingresos', category: 'money', forms: [],
    meaning: 'All the money that comes in from clients.',
    example: 'Revenue this month is higher than last month.' },
  { id: 'tariff', word: 'tariff', es: 'tarifa total cobrada', category: 'money',
    meaning: 'The total price charged for a load.',
    example: 'Check the total tariff before you send the invoice.' },
  { id: 'invoice', word: 'invoice', es: 'factura', category: 'money',
    forms: ['invoices', 'invoiced', 'invoicing'],
    meaning: 'A document asking a client to pay for a load.',
    example: 'Send the invoice after delivery.' },
  { id: 'overdue', word: 'overdue', es: 'vencido, atrasado', category: 'money', forms: [],
    meaning: 'Not paid or done by the date it should have been.',
    example: 'This client has two overdue invoices.' },
  { id: 'due', word: 'due', es: 'que vence, pendiente', category: 'money', forms: [],
    meaning: 'Must be paid or done by a certain date.',
    example: 'Payment is due in 30 days.' },
  { id: 'due-date', word: 'due date', es: 'fecha de vencimiento', category: 'money',
    meaning: 'The last day to pay or finish something.',
    example: 'The due date is the 15th.' },
  { id: 'payment-terms', word: 'payment terms', es: 'condiciones de pago', category: 'money', forms: [],
    meaning: 'The agreement about when and how a client pays.',
    example: 'Their payment terms are net 30.' },
  { id: 'net-30', word: 'net 30', es: 'pago a 30 días', category: 'money', forms: ['net 15', 'net 45', 'net 60'],
    meaning: 'The bill must be paid within 30 days (or 15, 45, 60).',
    example: 'The client pays net 30.' },
  { id: 'quick-pay', word: 'quick pay', es: 'pago rápido', category: 'money', forms: ['quickpay'],
    meaning: 'Paying a carrier early, usually for a small fee.',
    example: 'The carrier asked for quick pay.' },
  { id: 'factoring', word: 'factoring', es: 'factoraje', category: 'money', forms: [],
    meaning: 'A carrier sells its invoice to a company that pays it right away.',
    example: 'Send payment to the factoring company, not the carrier.' },
  { id: 'accessorial', word: 'accessorial', es: 'cargo adicional', category: 'money',
    meaning: 'An extra charge on top of the rate, like detention or a lumper.',
    example: 'Add the accessorials to the invoice.' },
  { id: 'detention', word: 'detention', es: 'cargo por tiempo de espera', category: 'money', forms: [],
    meaning: 'A charge when the truck waits too long to load or unload.',
    example: 'The driver waited five hours, so there is detention.' },
  { id: 'layover', word: 'layover', es: 'día de espera', category: 'money',
    meaning: 'When the truck must wait until the next day. The carrier charges for it.',
    example: 'The warehouse was closed, so we paid a layover.' },
  { id: 'lumper', word: 'lumper', es: 'descargador (y su cobro)', category: 'money',
    meaning: 'A worker paid to unload the truck at a warehouse. Also the fee for it.',
    example: 'The driver paid a $150 lumper.' },
  { id: 'tonu', word: 'TONU', es: 'pago por camión no utilizado', category: 'money', forms: [],
    meaning: 'Truck ordered, not used: a fee when a load is cancelled after the truck was sent.',
    example: 'The load was cancelled late, so we owe the carrier a TONU.' },
  { id: 'deadhead', word: 'deadhead', es: 'millas en vacío', category: 'money', forms: [],
    meaning: 'Miles a truck drives empty, for example to reach the pickup.',
    example: 'The truck has 80 miles of deadhead.' },
  { id: 'fee', word: 'fee', es: 'cargo, cuota', category: 'money',
    meaning: 'Money paid for a service.',
    example: 'There is a small fee for quick pay.' },
  { id: 'charge', word: 'charge', es: 'cargo, cobro', category: 'money',
    forms: ['charges', 'charged', 'charging'],
    meaning: 'An amount of money asked for. To charge is to ask for it.',
    example: 'The carrier charged us for detention.' },
  { id: 'balance', word: 'balance', es: 'saldo', category: 'money',
    meaning: 'How much money is still owed.',
    example: 'The client has a balance of $3,000.' },

  // ── Paperwork ─────────────────────────────────────────────────────────────
  { id: 'bill-of-lading', word: 'bill of lading', es: 'carta de porte, conocimiento de embarque',
    category: 'paperwork', forms: ['bills of lading', 'BOL', 'BOLs'],
    meaning: 'The BOL: the document that travels with the freight and lists what is on the truck.',
    example: 'The driver signs the BOL at pickup.' },
  { id: 'proof-of-delivery', word: 'proof of delivery', es: 'comprobante de entrega',
    category: 'paperwork', forms: ['proofs of delivery', 'POD', 'PODs'],
    meaning: 'The POD: the signed paper that shows the freight was delivered.',
    example: 'We cannot invoice until we have the POD.' },
  { id: 'rate-confirmation', word: 'rate confirmation', es: 'confirmación de tarifa',
    category: 'paperwork', forms: ['rate confirmations', 'rate con', 'rate cons'],
    meaning: 'The agreement the carrier signs: the load, the dates and what we pay them.',
    example: 'Send the rate confirmation to the carrier.' },
  { id: 'load-confirmation', word: 'load confirmation', es: 'confirmación de carga',
    category: 'paperwork',
    meaning: 'The agreement the client signs: the load, the dates and what they pay us.',
    example: 'The client must sign the load confirmation first.' },
  { id: 'agreement', word: 'agreement', es: 'acuerdo, contrato', category: 'paperwork',
    meaning: 'A document that both sides accept and sign.',
    example: 'The agreement was sent by email.' },
  { id: 'signature', word: 'signature', es: 'firma', category: 'paperwork',
    meaning: 'Your name written to show you agree.',
    example: 'We are still waiting for the client’s signature.' },
  { id: 'sign', word: 'sign', es: 'firmar', category: 'paperwork',
    forms: ['signs', 'signed', 'signing'],
    meaning: 'To put your signature on a document.',
    example: 'The carrier signed the rate confirmation.' },
  { id: 'unsigned', word: 'unsigned', es: 'sin firmar', category: 'paperwork', forms: [],
    meaning: 'Nobody has signed it yet.',
    example: 'You have three unsigned agreements.' },
  { id: 'waive', word: 'waive', es: 'dispensar, omitir', category: 'paperwork',
    forms: ['waived', 'waives', 'waiver'],
    meaning: 'To officially skip a rule, like the client’s signature.',
    example: 'Dispatch waived the signature for this load.' },
  { id: 'drivers-license', word: 'driver’s license', es: 'licencia de conducir', category: 'paperwork',
    forms: ['driver’s licenses', "driver's license", "driver's licenses", 'driver license', 'driver licenses'],
    meaning: 'The card that says a person may drive a truck.',
    example: 'Upload a photo of the driver’s license.' },
  { id: 'insurance', word: 'insurance', es: 'seguro', category: 'paperwork', forms: [],
    meaning: 'A policy that pays if something goes wrong, like damage or an accident.',
    example: 'Check the carrier’s insurance before you book them.' },
  { id: 'certificate-of-insurance', word: 'certificate of insurance', es: 'certificado de seguro',
    category: 'paperwork', forms: ['certificates of insurance', 'COI', 'COIs'],
    meaning: 'The COI: a paper that proves a carrier has insurance.',
    example: 'Ask the carrier for a new COI.' },
  { id: 'cargo-insurance', word: 'cargo insurance', es: 'seguro de carga', category: 'paperwork', forms: [],
    meaning: 'Insurance that pays if the freight is damaged or lost.',
    example: 'The carrier has $100,000 of cargo insurance.' },
  { id: 'liability', word: 'liability', es: 'responsabilidad civil', category: 'paperwork',
    forms: ['liabilities'],
    meaning: 'Insurance that pays if the truck hurts someone or damages their property.',
    example: 'Their liability insurance expires next month.' },
  { id: 'expire', word: 'expire', es: 'vencer, caducar', category: 'paperwork',
    forms: ['expires', 'expired', 'expiring', 'expiration', 'expiry'],
    meaning: 'To stop being valid after a date.',
    example: 'The insurance is expiring in ten days.' },
  { id: 'mc-number', word: 'MC number', es: 'número MC', category: 'paperwork',
    forms: ['MC numbers', 'MC'],
    meaning: 'The number the US government gives a company allowed to haul freight for others.',
    example: 'Search the carrier by MC number.' },
  { id: 'dot-number', word: 'DOT number', es: 'número DOT', category: 'paperwork',
    forms: ['DOT numbers', 'DOT'],
    meaning: 'The US Department of Transportation number for a trucking company.',
    example: 'Check the DOT number on the government website.' },
  { id: 'record', word: 'record', es: 'registro', category: 'paperwork',
    meaning: 'One saved entry, like an order, a carrier or a client.',
    example: 'Open the carrier’s record to see their phone number.' },
  { id: 'attachment', word: 'attachment', es: 'archivo adjunto', category: 'paperwork',
    forms: ['attachments', 'attach', 'attached', 'attaching'],
    meaning: 'A file added to a message or a record.',
    example: 'The BOL is attached to the email.' },
  { id: 'upload', word: 'upload', es: 'subir (un archivo)', category: 'paperwork',
    forms: ['uploads', 'uploaded', 'uploading'],
    meaning: 'To send a file from your computer to TTMS.',
    example: 'Upload the POD when you get it.' },
  { id: 'download', word: 'download', es: 'descargar', category: 'paperwork',
    forms: ['downloads', 'downloaded', 'downloading'],
    meaning: 'To save a file from TTMS onto your computer.',
    example: 'Download the invoice as a PDF.' },

  // ── Trucks and equipment ──────────────────────────────────────────────────
  { id: 'truck', word: 'truck', es: 'camión', category: 'trucks',
    meaning: 'The vehicle that pulls the trailer.',
    example: 'The truck broke down near Houston.' },
  { id: 'trailer', word: 'trailer', es: 'remolque, furgón', category: 'trucks',
    meaning: 'The long box or platform the truck pulls, where the freight goes.',
    example: 'The trailer is 53 feet long.' },
  { id: 'dry-van', word: 'dry van', es: 'furgón seco (sin refrigeración)', category: 'trucks',
    meaning: 'A closed trailer with no cooling.',
    example: 'This freight can go in a dry van.' },
  { id: 'reefer', word: 'reefer', es: 'furgón refrigerado', category: 'trucks',
    meaning: 'A trailer that keeps freight cold.',
    example: 'Frozen food needs a reefer.' },
  { id: 'flatbed', word: 'flatbed', es: 'plataforma', category: 'trucks',
    meaning: 'A trailer with no walls or roof, for big or heavy freight.',
    example: 'Steel beams go on a flatbed.' },
  { id: 'equipment', word: 'equipment', es: 'equipo, tipo de camión', category: 'trucks', forms: [],
    meaning: 'The kind of truck and trailer a load needs.',
    example: 'What equipment does the client need, van or reefer?' },
  { id: 'tarp', word: 'tarp', es: 'lona', category: 'trucks',
    meaning: 'A large sheet that covers freight on a flatbed.',
    example: 'The load must be tarped because of rain.' },
  { id: 'seal', word: 'seal', es: 'marchamo, sello', category: 'trucks',
    forms: ['seals', 'sealed'],
    meaning: 'A numbered lock on the trailer door. Only the consignee may break it.',
    example: 'Write the seal number on the BOL.' },
  { id: 'liftgate', word: 'liftgate', es: 'plataforma elevadora', category: 'trucks',
    meaning: 'A platform on the back of a truck that lifts freight up and down.',
    example: 'The consignee has no dock, so we need a liftgate.' },
  { id: 'mile', word: 'mile', es: 'milla (1.6 km)', category: 'trucks',
    forms: ['miles', 'mileage'],
    meaning: 'A US measure of distance. One mile is about 1.6 kilometres.',
    example: 'The lane is 900 miles.' },

  // ── Words on the screen ───────────────────────────────────────────────────
  { id: 'dashboard', word: 'dashboard', es: 'panel principal', category: 'screen',
    meaning: 'The first page you see: a summary of your work.',
    example: 'The dashboard shows your open loads.' },
  { id: 'settings', word: 'settings', es: 'configuración', category: 'screen', forms: [],
    meaning: 'The page where you change how things work.',
    example: 'Change the date format in Settings.' },
  { id: 'search', word: 'search', es: 'buscar, búsqueda', category: 'screen',
    forms: ['searches', 'searched', 'searching'],
    meaning: 'To look for something by typing a word.',
    example: 'Search the order by its number.' },
  { id: 'filter', word: 'filter', es: 'filtrar, filtro', category: 'screen',
    forms: ['filters', 'filtered', 'filtering'],
    meaning: 'To show only some items in a list.',
    example: 'Filter the list to show only delivered loads.' },
  { id: 'sort', word: 'sort', es: 'ordenar', category: 'screen', forms: ['sorted', 'sorting'],
    meaning: 'To put a list in order, for example by date or by name.',
    example: 'Sort the carriers by name.' },
  { id: 'save', word: 'save', es: 'guardar', category: 'screen', forms: ['saves', 'saved', 'saving'],
    meaning: 'To keep your changes.',
    example: 'Click Save before you leave the page.' },
  { id: 'submit', word: 'submit', es: 'enviar', category: 'screen',
    forms: ['submits', 'submitted', 'submitting'],
    meaning: 'To send a form when you have finished filling it in.',
    example: 'Submit the request to your manager.' },
  { id: 'edit', word: 'edit', es: 'editar', category: 'screen', forms: ['edits', 'edited', 'editing'],
    meaning: 'To change something that is already saved.',
    example: 'Edit the order to fix the pickup date.' },
  { id: 'delete', word: 'delete', es: 'eliminar, borrar', category: 'screen',
    forms: ['deletes', 'deleted', 'deleting'],
    meaning: 'To remove something for good.',
    example: 'Do not delete an order, cancel it.' },
  { id: 'remove', word: 'remove', es: 'quitar', category: 'screen',
    forms: ['removes', 'removed', 'removing'],
    meaning: 'To take something out or away.',
    example: 'Remove her from the work group.' },
  { id: 'assign', word: 'assign', es: 'asignar', category: 'screen',
    forms: ['assigns', 'assigned', 'assigning', 'assignment', 'assignments'],
    meaning: 'To give a job or a record to someone.',
    example: 'The carrier is assigned; now send the rate confirmation.' },
  { id: 'approve', word: 'approve', es: 'aprobar', category: 'screen',
    forms: ['approves', 'approved', 'approving', 'approval', 'approvals'],
    meaning: 'To say yes to a request.',
    example: 'Your manager approved the request.' },
  { id: 'request', word: 'request', es: 'solicitud, solicitar', category: 'screen',
    forms: ['requests', 'requested', 'requesting'],
    meaning: 'To ask for something. Also the thing you asked for.',
    example: 'Request access to the client from its owner.' },
  { id: 'pending', word: 'pending', es: 'pendiente', category: 'screen', forms: [],
    meaning: 'Waiting for something or someone. Not finished yet.',
    example: 'Your request is still pending.' },
  { id: 'required', word: 'required', es: 'obligatorio', category: 'screen', forms: ['require', 'requires'],
    meaning: 'You must fill it in or do it.',
    example: 'The pickup date is required.' },
  { id: 'available', word: 'available', es: 'disponible', category: 'screen',
    forms: ['availability', 'unavailable'],
    meaning: 'Ready or free to use. Unavailable means not ready or not free.',
    example: 'The truck is available tomorrow.' },
  { id: 'first-available', word: 'first available', es: 'primera fecha disponible', category: 'screen',
    forms: [],
    meaning: 'The earliest day the freight is ready to be picked up.',
    example: 'First available pickup is Monday.' },
  { id: 'suspended', word: 'suspended', es: 'suspendido', category: 'screen',
    forms: ['suspend', 'suspends', 'suspension'],
    meaning: 'Stopped for now. The person cannot sign in until it is lifted.',
    example: 'The account is suspended.' },
  { id: 'permission', word: 'permission', es: 'permiso', category: 'screen',
    meaning: 'Something TTMS lets you do or see.',
    example: 'You do not have permission to delete loads.' },
  { id: 'role', word: 'role', es: 'rol, puesto', category: 'screen',
    meaning: 'Your job in TTMS, like broker or dispatcher. It decides what you can do.',
    example: 'Her role is dispatcher.' },
  { id: 'access-list', word: 'access list', es: 'lista de acceso', category: 'screen',
    forms: ['allowlist'],
    meaning: 'The list of people allowed to sign in to TTMS.',
    example: 'Add the new broker to the access list.' },
  { id: 'sign-in', word: 'sign in', es: 'iniciar sesión', category: 'screen',
    forms: ['sign-in', 'signed in', 'signing in', 'log in', 'login', 'logged in'],
    meaning: 'To enter TTMS with your account.',
    example: 'Sign in with your company Google account.' },
  { id: 'sign-out', word: 'sign out', es: 'cerrar sesión', category: 'screen',
    forms: ['sign-out', 'signed out', 'log out', 'logout', 'logged out'],
    meaning: 'To leave TTMS so nobody else can use your account.',
    example: 'Sign out when you use a shared computer.' },
  { id: 'dismiss', word: 'dismiss', es: 'descartar, cerrar', category: 'screen',
    forms: ['dismissed', 'dismisses'],
    meaning: 'To close a message you have read.',
    example: 'Dismiss the alert once you have seen it.' },
  { id: 'reminder', word: 'reminder', es: 'recordatorio', category: 'screen',
    meaning: 'A message that helps you remember to do something.',
    example: 'Set a reminder to call the carrier.' },
  { id: 'overview', word: 'overview', es: 'resumen', category: 'screen', forms: [],
    meaning: 'A short summary of the main points.',
    example: 'The overview shows this month’s numbers.' },
  { id: 'handbook', word: 'handbook', es: 'manual', category: 'screen',
    meaning: 'A guide that explains how things work here.',
    example: 'The answer is in the handbook.' },
  { id: 'onboarding', word: 'onboarding', es: 'inducción', category: 'screen', forms: [],
    meaning: 'The first weeks of a new job, learning how everything works.',
    example: 'Finish your onboarding survey this week.' },
  { id: 'survey', word: 'survey', es: 'encuesta', category: 'screen',
    meaning: 'A list of questions to find out what people think.',
    example: 'Please fill in the survey.' },
  { id: 'task', word: 'task', es: 'tarea', category: 'screen',
    meaning: 'A piece of work to do.',
    example: 'You have two tasks left.' },
  { id: 'work-anniversary', word: 'work anniversary', es: 'aniversario laboral', category: 'screen',
    forms: ['work anniversaries'],
    meaning: 'The day you started at the company, each year.',
    example: 'Today is her fifth work anniversary.' },
  { id: 'pin', word: 'pin', es: 'fijar', category: 'screen',
    forms: ['pins', 'pinned', 'pinning', 'unpin'],
    meaning: 'To keep a message at the top so it is easy to find.',
    example: 'Pin the new rates to the room.' },
  { id: 'thread', word: 'thread', es: 'hilo (de conversación)', category: 'screen',
    meaning: 'Replies to one message, kept together under it.',
    example: 'Answer in the thread, not in the main chat.' },
  { id: 'mute', word: 'mute', es: 'silenciar', category: 'screen', forms: ['mutes', 'muted', 'muting'],
    meaning: 'To stop sounds or alerts, or to stop someone writing for a time.',
    example: 'Mute the room if it is too noisy.' },
  { id: 'room', word: 'room', es: 'sala (de chat)', category: 'screen',
    meaning: 'A group chat.',
    example: 'Post the update in the dispatch room.' },
  { id: 'reply', word: 'reply', es: 'responder, respuesta', category: 'screen',
    forms: ['replies', 'replied', 'replying'],
    meaning: 'To answer a message. Also the answer itself.',
    example: 'Reply to the carrier’s email.' },
  { id: 'unread', word: 'unread', es: 'no leído', category: 'screen', forms: [],
    meaning: 'You have not opened it yet.',
    example: 'You have five unread messages.' },

  // ── Office English ────────────────────────────────────────────────────────
  { id: 'asap', word: 'ASAP', es: 'lo antes posible', category: 'office', forms: [],
    meaning: 'As soon as possible.',
    example: 'I need the POD ASAP.' },
  { id: 'fyi', word: 'FYI', es: 'para tu información', category: 'office', forms: [],
    meaning: 'For your information: something you should know, no action needed.',
    example: 'FYI, the client changed the delivery date.' },
  { id: 'eod', word: 'EOD', es: 'fin del día', category: 'office', forms: [],
    meaning: 'End of day: before you go home today.',
    example: 'Send me the numbers by EOD.' },
  { id: 'follow-up', word: 'follow up', es: 'dar seguimiento', category: 'office',
    forms: ['follow-up', 'follow-ups', 'followed up', 'following up', 'follows up'],
    meaning: 'To check again later on something that is not finished.',
    example: 'Follow up with the carrier about the POD.' },
  { id: 'heads-up', word: 'heads up', es: 'aviso', category: 'office', forms: ['heads-up'],
    meaning: 'A warning so someone is ready for something.',
    example: 'Heads up: the warehouse closes early today.' },
  { id: 'touch-base', word: 'touch base', es: 'ponerse en contacto', category: 'office',
    forms: ['touching base', 'touched base'],
    meaning: 'To talk briefly to check how things are going.',
    example: 'Let’s touch base after lunch.' },
  { id: 'out-of-office', word: 'out of office', es: 'fuera de la oficina', category: 'office',
    forms: ['OOO'],
    meaning: 'Not at work, for example on holiday.',
    example: 'I am out of office on Friday.' },
  { id: 'shift', word: 'shift', es: 'turno', category: 'office',
    meaning: 'The hours you work on a day.',
    example: 'My shift ends at 5 pm.' },
  { id: 'update', word: 'update', es: 'actualización, actualizar', category: 'office',
    forms: ['updates', 'updated', 'updating'],
    meaning: 'New information. To update is to give or add it.',
    example: 'Can you give me an update on the load?' },
  { id: 'issue', word: 'issue', es: 'problema', category: 'office',
    meaning: 'A problem.',
    example: 'The driver had an issue with the truck.' },
  { id: 'confirm', word: 'confirm', es: 'confirmar', category: 'office',
    forms: ['confirms', 'confirmed', 'confirming', 'confirmation', 'confirmations'],
    meaning: 'To say that something is true or agreed.',
    example: 'Please confirm the pickup time.' },
  { id: 'schedule', word: 'schedule', es: 'programar, horario', category: 'office',
    forms: ['schedules', 'scheduled', 'scheduling'],
    meaning: 'A plan of times. To schedule is to set a time for something.',
    example: 'The pickup is scheduled for 8 am.' },
  { id: 'deadline', word: 'deadline', es: 'fecha límite', category: 'office',
    meaning: 'The latest time something must be done.',
    example: 'The deadline for the invoice is Friday.' },
];

export const GLOSSARY_BY_ID: ReadonlyMap<string, GlossaryTerm> =
  new Map(GLOSSARY.map((t) => [t.id, t]));

export function isGlossaryId(value: unknown): value is string {
  return typeof value === 'string' && GLOSSARY_BY_ID.has(value);
}

/**
 * The regular English plural, which covers every noun on the list that does
 * not spell its own forms out. Irregular ones (party → parties is regular;
 * a few like "bills of lading" are not) are written into `forms` instead.
 */
function pluralOf(word: string): string {
  if (/[^aeiou]y$/i.test(word)) return word.slice(0, -1) + 'ies';
  if (/(s|x|z|ch|sh)$/i.test(word)) return word + 'es';
  return word + 's';
}

export function formsOf(term: GlossaryTerm): string[] {
  return [term.word, ...(term.forms ?? [pluralOf(term.word)])];
}

/** All capitals, like BOL or ETA: matched only exactly as written. */
export function isAcronym(form: string): boolean {
  return /^[A-Z]{2,}s?$/.test(form);
}
